export const SUN_RADIUS = 0.55

// segments: sphere detail level [widthSeg, heightSeg]
export const PLANETS = [
  {
    name: 'Mercury',
    radius: 0.055,
    orbitRadius: 1.5,
    orbitSpeed: 0.0047,
    tilt: 0.034,
    initialAngle: 0.0,
    textureUrl: '/textures/planets/mercury.jpg',
    color: '#b5b5b5',
    segments: [96, 96],
    role: 'Signal Relay',
    unlock: 'Verification Sources',
    fact: 'Closest relay to the Sun. Visit Mercury to begin proving signals like email, phone, and documents.',
    appUrl: 'https://chat.zerosoils.com',
    appName: 'Chat Terminal',
  },
  {
    name: 'Venus',
    radius: 0.10,
    orbitRadius: 2.2,
    orbitSpeed: 0.0035,
    tilt: 177.4,
    initialAngle: 1.3,
    textureUrl: '/textures/planets/venus.jpg',
    color: '#e8cda0',
    segments: [96, 96],
    role: 'Consent Layer',
    unlock: 'Permission Engine',
    fact: 'Venus governs consent. Verified users tune what their HDI can view, share, transfer, or claim.',
    appUrl: 'https://id.zerosoils.com',
    appName: 'ZeroSoils Identity',
  },
  {
    name: 'Earth',
    radius: 0.115,
    orbitRadius: 3.0,
    orbitSpeed: 0.0029,
    tilt: 23.5,
    initialAngle: 2.7,
    textureUrl: '/textures/earth_day.jpg',
    isEarth: true,
    color: '#4da6ff',
    segments: [128, 128],
    role: 'Network Hub',
    unlock: 'Protocol Explorer',
    fact: 'Earth is the entry point to the sovereign network. Explore the core protocol, nodes, and ecosystem here.',
  },
  {
    name: 'Mars',
    radius: 0.075,
    orbitRadius: 4.0,
    orbitSpeed: 0.0024,
    tilt: 25.2,
    initialAngle: 0.4,
    textureUrl: '/textures/planets/mars.jpg',
    color: '#c1440e',
    segments: [96, 96],
    role: 'Recovery Vault',
    unlock: 'Recovery Protocol',
    fact: 'Mars stores resilience. Configure guardians, family recovery, time locks, and multisig routes here.',
    appUrl: 'https://coin.zerosoils.com',
    appName: 'RupeeCoin',
  },
  {
    name: 'Jupiter',
    radius: 0.36,
    orbitRadius: 5.8,
    orbitSpeed: 0.0013,
    tilt: 3.13,
    initialAngle: 1.8,
    textureUrl: '/textures/planets/jupiter.jpg',
    color: '#c88b3a',
    segments: [128, 128],
    role: 'Trust Graph',
    unlock: 'Relationship Graph',
    fact: 'Jupiter expands trust through family, friends, professional links, and social verification.',
    appUrl: 'https://pay.zerosoils.com',
    appName: 'PayEngine',
  },
  {
    name: 'Saturn',
    radius: 0.30,
    orbitRadius: 7.8,
    orbitSpeed: 0.0009,
    tilt: 26.73,
    initialAngle: 3.5,
    textureUrl: '/textures/planets/saturn.jpg',
    hasRings: true,
    color: '#e4d191',
    segments: [128, 128],
    role: 'Asset Rings',
    unlock: 'Digital Asset Ownership',
    fact: 'Saturn links wallets, domains, credentials, and documents into rings around your HDI.',
    appUrl: 'https://play.zerosoils.com',
    appName: 'Ludo',
  },
  {
    name: 'Uranus',
    radius: 0.20,
    orbitRadius: 9.8,
    orbitSpeed: 0.00064,
    tilt: 97.77,
    initialAngle: 5.2,
    textureUrl: '/textures/planets/uranus.jpg',
    color: '#7de8e8',
    segments: [96, 96],
    role: 'Privacy Tilt',
    unlock: 'Selective Disclosure',
    fact: 'Uranus turns disclosure sideways: decide what becomes public and what stays private.',
    appUrl: 'https://biz.zerosoils.com',
    appName: 'Jhon Aamit LLP',
  },
  {
    name: 'Neptune',
    radius: 0.19,
    orbitRadius: 11.5,
    orbitSpeed: 0.0005,
    tilt: 28.32,
    initialAngle: 4.1,
    textureUrl: '/textures/planets/neptune.jpg',
    color: '#4b70dd',
    segments: [96, 96],
    role: 'Sovereign Edge',
    unlock: 'Identity Export',
    fact: 'Neptune is the sovereign edge. Export your identity and carry the credential beyond the system.',
    appUrl: 'https://nyf.zerosoils.com',
    appName: 'National Youth Force',
  },
]

// Moon — orbits Earth
export const MOON = {
  name: 'Moon',
  radius: 0.031,
  orbitRadius: 0.38,
  orbitSpeed: 0.0095,
  initialAngle: 0.8,
  textureUrl: '/textures/planets/mercury.jpg', // gray rocky stand-in
  color: '#d4d0c8',
  segments: [64, 64],
  role: 'Earth Gateway',
  unlock: 'Lunar Verification',
  fact: "Earth's closest satellite and the first checkpoint for identity verification beyond Earth. The Moon bridges terrestrial protocol and deep-space sovereignty.",
  isMoon: true,
}

// Sun data (rendered via Sun.jsx; this is used for nav + PlanetPage)
export const SUN_DATA = {
  name: 'Sun',
  textureUrl: '/textures/planets/sun.jpg',
  color: '#ffaa22',
  role: 'Protocol Source',
  unlock: 'Genesis Access',
  fact: 'The origin of all sovereign energy. The Sun powers every node in the digital universe and maintains the gravitational truth of the entire protocol.',
  appUrl: 'https://jarvis.zerosoils.com',
  appName: 'Jarvis AI',
}

// Sun as a tour stop — registered via planetRefs in Sun.jsx
export const SUN_STOP = {
  name: 'Sun',
  fact: 'The source of the protocol. Arrival starts here before your HDI travels across the universe.',
}

export const GALAXY_STOP = {
  name: 'Milky Way',
  fact: 'The wider internet. Your HDI is designed to travel beyond one app, one planet, or one platform.',
}
